### ISSUE TITLE
Scroll get stuck after changing season in tv show page

### ISSUE THREAD

**Issue by ompel** [PopcornRepos/PopcornTimeOnline#1]
When first getting inside a TV show, you can scroll the episodes but after changing to a different season, IScroll get stuck.
Console throws that error:

Uncaught TypeError: Cannot read property 'removeChild' of nullIndicator.destroy @ iscroll.js:1712(anonymous function) @ iscroll.js:1014_indicatorsMap @ iscroll.js:975(anonymous function) @ iscroll.js:1013IScroll._execEvent @ iscroll.js:739IScroll.destroy @ iscroll.js:363ui.tv.set_season @ ui.tv_show.js?cb=01:87onclick @ (index):1me.click @ iscroll.js:241IScroll._end @ iscroll.js:564IScroll.handleEvent @ iscroll.js:1553

**Comment by slav4o** [comment]
@ompel  i have the same issue did you get it fixed ?
