### ISSUE TITLE
WebSocket connection issue

### ISSUE THREAD

**Issue by kaludjer** [PopcornRepos/PopcornTimeOnline#28]
I can't get any content and I got  this error in console:
WebSocket connection to 'wss://localhost.ttconfig.xyz:9220/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED

I installed SSL but it still doesn't work.

Any suggestion?

**Comment by vaporwavie** [comment]
Did you tried accessing this address directly?

**Comment by kaludjer** [comment]
If I open wss://localhost.ttconfig.xyz:9220 directly in browser it says "This site can't be reached."

Here is version that makes problem [(http://dpopovic.com/pp/)](http://dpopovic.com/pp/)

**Comment by vaporwavie** [comment]
I'd recommend you to check the plugin one more time. Perhaps something on it isn't configured properly. Unfortunately I can't test it right now, due the fact that it requires a Windows installation. But try to reinstall it :)

**Comment by kaludjer** [comment]
It works on localhost. I think problem is on the srv. Thanks anyway.

**Comment by vaporwavie** [comment]
Yeah, probably. This repository is pretty much dead, so all the external stuff related to it might be buried as well. If you may, consider closing this issue. :)
